from Game import BlackjackGame
def main():
    input("Welcome to Blackjack (or 21)! Press eneter to continue.:")
    rules = input("Before we start, do you want to know the rules of Blackjack first? Input y or yes here: ")
    rules = rules.upper()
    if rules == "Y" or rules == "YES":
        input("Blackjack is a game of math, probability, and some luck.")
        input("The goal of the game is for your hand's total points be 21 or closer to 21 but no more than that.")
        input("If your total points go over 21, your hand is now a bust, meaning you automatically lose.")
        input("if your total points add to 21, you will either win or draw, which we will get into later.")
        input("Now, there could be up to 7 players in this game, but you'll only go up against the dealer")
        input("The dealer's goal is the same as yours, meaning to win this game, not only must your hand must total to 21 or less. But must be also greater than the dealer's.")
        input("Initially, all players will be given $10000 in their balance.")
        input("At the start of each round, players will make a bet. Make sure the bet does not exceed your current balance.")
        input("The dealer will then give each player 2 cards facing up, while the dealer deals themselves 1 card facing up, and another facing down.")
        input("Each card has points. Cards with numbers are scored by their face value (Dueces give 2 points, 7's give 7 points) while Jacks, Queens, and Kings offer 10 points.")
        input("Aces give either 1 or 11 points, depending on which is more favorable to the player/dealer.")
        input("Note that the suit does not matter in this game")
        input("Now if at the start of the round, if one or more players has a blackjack (Having an Ace and a card with 10 points), they will automatically win, unless the dealer also has a blackjack, which is a push for them (draw).")
        input("By the way, in a push, you get your money back.")
        input("But if the dealer also reveals to have a blackjack, all active players lose apart from players who also have a blackjack., which results to a push for them.")
        input("After the initial deal, each player will be asked if they want to hit (1) or to stand (2).")
        input("Hit means you'll be given a card, adding more points to your total. You can hit until you get 21 points or bust. Stand just ends your turn prematurely.")
        input("After all players have been given the opportunity to hit and stand, players who bust are now out of the game for the current round. Now, it's the dealer's turn.")
        input("The dealer will now reveal their card. If the total value is less than 17, they will hit until they score 17 or more.")
        input("Now if the player and the dealer neither got a blackjack nor got bust, they will compare the scores of their hand. The hand closer to 21 wins.")
        input("Remember that you're only up against the dealer, so you only need to score higher than the dealer.")
        input("If you win, great. You receive double the amount you betted. If you didn't, you lose the amount you betted.")
        input("You'll be eliminated if you have a balance of 0 (or less if you do somehow) or you voluntarily quit after the round ended.")
        input("Once all broke players and players who cashed out have been eliminated, the cards are reshuffled and the game starts all over again. Now that you know the rules, let's go gambling!")

    new_game = BlackjackGame()
    new_game.start()
    
main()